version: '3'

services:
  proxymanager:
    build: .
    volumes:
      - ./app:/app
    container_name: proxymanager
    ports:
      - 0.0.0.0:3000:8080
      
  s1:
    image: nginx:latest
    container_name: s1
    volumes:
      - ./example/s1:/usr/share/nginx/html
    ports:
      - 0.0.0.0:3001:80

  s2:
    image: nginx:latest
    container_name: s2
    volumes:
      - ./example/s2:/usr/share/nginx/html
    ports:
      - 0.0.0.0:3002:80
